<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_externalContentHost4</name>
   <tag></tag>
   <elementGuidId>3b6036f7-3bc7-4d6f-8ac1-fad6c3e8cb2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;externalContentHost4&quot;)[count(. | //iframe[@src = 'http://syedsaad:8028/VSOInteGreat4TFS/IndexForVSTS?selectedTab=simulation&amp;adminHubId=collection-level-admin-hub']) = count(//iframe[@src = 'http://syedsaad:8028/VSOInteGreat4TFS/IndexForVSTS?selectedTab=simulation&amp;adminHubId=collection-level-admin-hub'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>external-content-iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>externalContentHost4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>externalContentHost4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://syedsaad:8028/VSOInteGreat4TFS/IndexForVSTS?selectedTab=simulation&amp;adminHubId=collection-level-admin-hub</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;externalContentHost4&quot;)</value>
   </webElementProperties>
</WebElementEntity>
