<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_SmartReport-table</name>
   <tag></tag>
   <elementGuidId>b11c70e9-72d4-47f5-8cbf-717a1ce1be7f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jqx-cell jqx-grid-cell jqx-item jqx-grid-cell-nowrap ig-smartReport-File jqx-fill-state-hover jqx-grid-cell-hover</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SmartReport-table</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row4rpt-mp-jqxSelectReportDropDownTree&quot;)/td[@class=&quot;jqx-cell jqx-grid-cell jqx-item jqx-grid-cell-nowrap ig-smartReport-File jqx-fill-state-hover jqx-grid-cell-hover&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TFSEmbed/Modules Objects/Reporting/Create report with sample template/Page_Reporting - Microsoft Team Fou (3)/iframe_externalContentHost4</value>
   </webElementProperties>
</WebElementEntity>
