<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ig-diag-bottom-pane</name>
   <tag></tag>
   <elementGuidId>d18f3619-b578-49fd-af8d-1038c63e9b7a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ig-diag-bottom-pane</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ig-newfile-window-content-bot-new-file-dialog&quot;)/div[1]/div[1]/div[4]/div[1]/div[@class=&quot;ig-diag-bottom-pane&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VSTS/Modules Objects/Alice BOT/new chat/Page_Alice (Bot) - Visual Studio Te/iframe_externalContentHost180</value>
   </webElementProperties>
</WebElementEntity>
