<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>7b475af9-db52-4ce0-a2a9-33312cbef89c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;confirm-dialog-ok-button-mdl-confirmation-dialog&quot;)[count(. | //button[@id = 'confirm-dialog-ok-button-mdl-confirmation-dialog' and @onclick = 'onConfirmationDialogOkButtonClick(this)' and (text() = 'OK' or . = 'OK')]) = count(//button[@id = 'confirm-dialog-ok-button-mdl-confirmation-dialog' and @onclick = 'onConfirmationDialogOkButtonClick(this)' and (text() = 'OK' or . = 'OK')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ig-ui-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm-dialog-ok-button-mdl-confirmation-dialog</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>onConfirmationDialogOkButtonClick(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parentcontainerid</name>
      <type>Main</type>
      <value>mdl-confirmation-dialog</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm-dialog-ok-button-mdl-confirmation-dialog&quot;)</value>
   </webElementProperties>
</WebElementEntity>
