<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ig-AddNewLinkedWi-WiTitl</name>
   <tag></tag>
   <elementGuidId>f35aa727-c869-4cf3-9750-bfeffd8c8e48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ig-AddNewLinkedWi-WiTitle-ig-AllLinks-AddNewLinkedWorkitem-Dialog-dia_allLinks&quot;)[count(. | //input[@id = 'ig-AddNewLinkedWi-WiTitle-ig-AllLinks-AddNewLinkedWorkitem-Dialog-dia_allLinks' and @placeholder = 'Enter work item title' and @data-parentcontainerid = 'ig-AllLinks-AddNewLinkedWorkitem-Dialog-dia_allLinks' and @onkeyup = 'AddNewLinkedWorkItem.onTitleChanged(event, this)' and @oninput = 'AddNewLinkedWorkItem.onTitleChanged(event, this)']) = count(//input[@id = 'ig-AddNewLinkedWi-WiTitle-ig-AllLinks-AddNewLinkedWorkitem-Dialog-dia_allLinks' and @placeholder = 'Enter work item title' and @data-parentcontainerid = 'ig-AllLinks-AddNewLinkedWorkitem-Dialog-dia_allLinks' and @onkeyup = 'AddNewLinkedWorkItem.onTitleChanged(event, this)' and @oninput = 'AddNewLinkedWorkItem.onTitleChanged(event, this)'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ig-AddNewLinkedWi-WiTitle-ig-AllLinks-AddNewLinkedWorkitem-Dialog-dia_allLinks</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ig-AddNewLinkedWi-TitleFieldStyle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter work item title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parentcontainerid</name>
      <type>Main</type>
      <value>ig-AllLinks-AddNewLinkedWorkitem-Dialog-dia_allLinks</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>AddNewLinkedWorkItem.onTitleChanged(event, this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>AddNewLinkedWorkItem.onTitleChanged(event, this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ig-AddNewLinkedWi-WiTitle-ig-AllLinks-AddNewLinkedWorkitem-Dialog-dia_allLinks&quot;)</value>
   </webElementProperties>
</WebElementEntity>
