<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ig-AddNewLinkedWi-AddNewLi</name>
   <tag></tag>
   <elementGuidId>d53ae2d1-371c-4ab0-8209-1d3f728d137b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ig-AddNewLinkedWi-AddNewLinkedWiDialogWindowBottomDiv-ig-AllLinks-AddNewLinkedWorkitem-Dialog-dia_allLinks</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ig-diag-bottom-pane</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ig-AddNewLinkedWi-AddNewLinkedWiDialogWindowBottomDiv-ig-AllLinks-AddNewLinkedWorkitem-Dialog-dia_allLinks&quot;)</value>
   </webElementProperties>
</WebElementEntity>
