<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Reporting (1)</name>
   <tag></tag>
   <elementGuidId>e6a1c557-a310-48a3-9fba-e9db54f35a51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[id$='edevtech-mr.iGVSO-OnPrem-001.subHubWork-AdvReport-OnPrem'] span.text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reporting</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mi_213_edevtech-mr.iGVSO-OnPrem-001.subHubWork-AdvReport-OnPrem&quot;)/span[@class=&quot;text&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>ends with</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edevtech-mr.iGVSO-OnPrem-001.subHubWork-AdvReport-OnPrem</value>
   </webElementProperties>
</WebElementEntity>
