<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_name</name>
   <tag></tag>
   <elementGuidId>b11f4320-2e9b-4848-b0f3-3d4c18339693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/ol[1]/li[2]/a[@class=&quot;uc-SmartTagLink&quot;]/span[@class=&quot;uc-smartTagWorkItemTitle&quot;][count(. | //span[@ref_element = 'Object Repository/TFSEmbed/Modules Objects/Use Case/Using Smarttag/Page_Simulation and Use case - Micr (1)/iframe_rteSample_Iframe']) = count(//span[@ref_element = 'Object Repository/TFSEmbed/Modules Objects/Use Case/Using Smarttag/Page_Simulation and Use case - Micr (1)/iframe_rteSample_Iframe'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uc-smartTagWorkItemTitle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ol[1]/li[2]/a[@class=&quot;uc-SmartTagLink&quot;]/span[@class=&quot;uc-smartTagWorkItemTitle&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TFSEmbed/Modules Objects/Use Case/Using Smarttag/Page_Simulation and Use case - Micr (1)/iframe_rteSample_Iframe</value>
   </webElementProperties>
</WebElementEntity>
