<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SmartNote</name>
   <tag></tag>
   <elementGuidId>6833c22b-e94d-4b0d-90a1-9e24eadf2377</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[count(. | //*[text() = 'SmartNote']) = count(//*[text() = 'SmartNote'])][count(. | id(&quot;mi_244_syedsaad.iGVSO-OnPrem-001.subHubWork-SmartNote-OnPrem&quot;)/span[@class=&quot;text&quot;]) = count(id(&quot;mi_244_syedsaad.iGVSO-OnPrem-001.subHubWork-SmartNote-OnPrem&quot;)/span[@class=&quot;text&quot;])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mi_241_syedsaad\2e iGVSO-OnPrem-001\2e subHubWork-SmartNote-OnPrem > span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SmartNote</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mi_244_syedsaad.iGVSO-OnPrem-001.subHubWork-SmartNote-OnPrem&quot;)/span[@class=&quot;text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
