<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dia-okBtn</name>
   <tag></tag>
   <elementGuidId>4d6ac89d-7b82-4760-9cce-9eabd7806ec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;dia_ej-edevDiagram-diagramtemplate-popup&quot;)/div[@class=&quot;dia-e-edevDiagram-template-container&quot;]/div[@class=&quot;dia-footer-container&quot;]/div[@class=&quot;dia-button-container&quot;]/input[@class=&quot;dia-okBtn&quot;][count(. | //input[@type = 'button']) = count(//input[@type = 'button'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Create</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dia-okBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dia_ej-edevDiagram-diagramtemplate-popup&quot;)/div[@class=&quot;dia-e-edevDiagram-template-container&quot;]/div[@class=&quot;dia-footer-container&quot;]/div[@class=&quot;dia-button-container&quot;]/input[@class=&quot;dia-okBtn&quot;]</value>
   </webElementProperties>
</WebElementEntity>
