<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_</name>
   <tag></tag>
   <elementGuidId>c0b8cb73-e680-439f-87bc-5f90aa279a8e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-name</name>
      <type>Main</type>
      <value>ChevronDown</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-47 root-44 ms-Button-icon chevron-Icon is-collapsed icon-36</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vss_1&quot;)/div[@class=&quot;internal-content-host&quot;]/div[@class=&quot;project-hub-component&quot;]/div[@class=&quot;project-list-component&quot;]/div[@class=&quot;ms-Fabric hub-view-component ms-u-fadeIn200 css-32&quot;]/div[@class=&quot;hub-view-content&quot;]/ul[@class=&quot;hub-groups&quot;]/li[2]/div[@class=&quot;hub-group&quot;]/div[@class=&quot;ms-Viewport&quot;]/div[@class=&quot;ms-DetailsList root_ec8f954f&quot;]/div[1]/div[2]/div[@class=&quot;ms-FocusZone focusZone_ec8f954f&quot;]/div[@class=&quot;ms-SelectionZone&quot;]/div[@class=&quot;ms-List&quot;]/div[@class=&quot;ms-List-surface&quot;]/div[@class=&quot;ms-List-page&quot;]/div[@class=&quot;ms-List-cell&quot;]/div[@class=&quot;is-active&quot;]/div[@class=&quot;ms-FocusZone ms-DetailsRow css-41 root_1f19677d owner_4d4e6f77 is-selected isSelected_4d4e6f77 rootIsSelected_1f19677d&quot;]/div[@class=&quot;ms-DetailsRow-fields fields_1f19677d&quot;]/div[@class=&quot;ms-DetailsRow-cell cell_1f19677d project-column-title&quot;]/div[@class=&quot;project-team-title team-level-0&quot;]/button[@class=&quot;ms-Button ms-Button--icon project-team-toggle-button root-42&quot;]/div[@class=&quot;ms-Button-flexContainer flexContainer-34&quot;]/i[@class=&quot;css-47 root-44 ms-Button-icon chevron-Icon is-collapsed icon-36&quot;]</value>
   </webElementProperties>
</WebElementEntity>
