<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NewScrumTeam</name>
   <tag></tag>
   <elementGuidId>ebf0014b-4a00-4de9-b088-8a2f29e0fbb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'draggable jqx-rc-all jqx-tree-item jqx-item jqx-draggable jqx-fill-state-hover jqx-tree-item-hover' and @id = 'jqxWidget771216b7' and @ref_element = 'Object Repository/VSTS/Modules Objects/Backlog/Review Record/Project dropdown and date/Page_Backlog items/iframe_externalContentHost618']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>draggable jqx-rc-all jqx-tree-item jqx-item jqx-draggable jqx-fill-state-hover jqx-tree-item-hover</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqxWidget771216b7</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NewScrum\Team</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqxWidget771216b7&quot;)</value>
   </webElementProperties>
</WebElementEntity>
