<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Folder</name>
   <tag></tag>
   <elementGuidId>b7dbeb69-68c2-47b8-9c25-79af5a90bd1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#smd-left-pane-new-folder > span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'smd-left-pane-new-folder' and @ref_element = 'Object Repository/TFSEmbed/Modules Objects/Smart Docs/FolderCreation/iframe_externalContentHost4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Folder</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;smd-left-pane-new-folder&quot;)/span[@class=&quot;k-link&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>smd-left-pane-new-folder</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TFSEmbed/Modules Objects/Smart Docs/FolderCreation/iframe_externalContentHost4</value>
   </webElementProperties>
</WebElementEntity>
