<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ig-NewBaselineDialog-txt</name>
   <tag></tag>
   <elementGuidId>96339b94-f7f1-4728-bf2a-b9a1219b8970</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ig-NewBaselineDialog-txtBaselineLabel-ig-vsts-create-baseline&quot;)[count(. | //*[@ref_element = 'Object Repository/VSTS/Modules Objects/Backlog/Baseline TextBox/iframe_externalContentHost481']) = count(//*[@ref_element = 'Object Repository/VSTS/Modules Objects/Backlog/Baseline TextBox/iframe_externalContentHost481'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ig-NewBaselineDialog-txtBaselineLabel-ig-vsts-create-baseline</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>newBaselineDialog.onNewBaselineEnterPress(event, this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parentcontainerid</name>
      <type>Main</type>
      <value>ig-vsts-create-baseline</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ig-NewBaselineDialog-txtBaselineLabel-ig-vsts-create-baseline&quot;)</value>
   </webElementProperties>
</WebElementEntity>
