<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Alice (Bot)</name>
   <tag></tag>
   <elementGuidId>ff6265c4-fd0f-4713-b327-cb658c30d159</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mi_128_syedsaad.iGVSO-OnPrem-001.subHubWork-AliceBot-OnPrem&quot;)/span[@class=&quot;text&quot;][count(. | //span[(text() = 'Alice (Bot)' or . = 'Alice (Bot)')]) = count(//span[(text() = 'Alice (Bot)' or . = 'Alice (Bot)')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alice (Bot)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mi_128_syedsaad.iGVSO-OnPrem-001.subHubWork-AliceBot-OnPrem&quot;)/span[@class=&quot;text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
