<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_k-virtual-scrollable-wrap</name>
   <tag></tag>
   <elementGuidId>1a716a44-e193-4d05-9e76-3098fbb8c8c2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-virtual-scrollable-wrap</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rvm-req-workitemgrid&quot;)/div[@class=&quot;k-grid-content&quot;]/div[@class=&quot;k-virtual-scrollable-wrap&quot;]</value>
   </webElementProperties>
</WebElementEntity>
