<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li</name>
   <tag></tag>
   <elementGuidId>1e362484-75ac-4b7b-bb0f-4278f300366c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body > ol > li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/ol[1]/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ol[1]/li[1]</value>
   </webElementProperties>
</WebElementEntity>
