<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Page</name>
   <tag></tag>
   <elementGuidId>a140f9f2-1a3c-4d99-af0e-9a18d5da158a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[text() = 'Page'][count(. | id(&quot;snt-left-pane-new-smartnote&quot;)/span[@class=&quot;k-link&quot;]) = count(id(&quot;snt-left-pane-new-smartnote&quot;)/span[@class=&quot;k-link&quot;])][count(. | //*[@ref_element = 'Object Repository/VSTS/Modules Objects/Smart Note/Page_SmartNote - Visual Studio Team (3)/iframe_externalContentHost4']) = count(//*[@ref_element = 'Object Repository/VSTS/Modules Objects/Smart Note/Page_SmartNote - Visual Studio Team (3)/iframe_externalContentHost4'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Page</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snt-left-pane-new-smartnote&quot;)/span[@class=&quot;k-link&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VSTS/Modules Objects/Smart Note/Page_SmartNote - Visual Studio Team (3)/iframe_externalContentHost4</value>
   </webElementProperties>
</WebElementEntity>
